### ISSUE TITLE
VW MEB Voltage or current changed with car software  3.2 exworks

### ISSUE THREAD

**Issue by MattiJarvinen** [iternio/ev-obd-pids#6]
VW MEB Voltage or current changed with car software  3.2 exworks.

On my ID.4 2021 after 3.2 got installed in VW maintenance used power calculations are way off in EVNotify. Since if I recall ABRP and EVNotify both use @spot2000 PIDS and math this might be a problem for your users driving any MEB car and using Bluetooth BLE.

![Screenshot_2023-05-25-13-30-38-16_72f9bf613b353d1f1d75fc1b9ca11c2f](https://github.com/iternio/ev-obd-pids/assets/12794435/0eb651ab-8217-48b4-88f6-bf6a0928334e)

**Comment by SamuelBrucksch** [comment]
3.2 has multi frame messages for current. This is already handled correctly in ABRP

**Comment by MattiJarvinen** [comment]
The PID in question nor the calculation hasn't changed in this repository in two years. So the data presented by this repository is incorrect?

**Comment by SamuelBrucksch** [comment]
It's not the pid or calculation that changed, but the way the data is returned from the car. Also these files are not always up to date with the latest version we have internally.

**Comment by MattiJarvinen** [comment]
Nice to know, I know how multiframe responses are parsed so maybe I can get EVNotify fixed to restore legacy BT support to ABRP.
